config/routes.rb
Matrix::Application.routes.draw do
  resources :stories

  resources :entities

  devise_for :users
  
  root :to => "entities#index"
  
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

     def initialize(user)
       user ||= User.new # guest user (not logged in)
       if user.role?
         can :manage, :all if user.role == "admin"
       else
         can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/entity.rb
class Entity < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  
  def entity_name(entity_type)
    if entity_type == 1
      "Person"
    else
      "Company"
    end
  end
  
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
    #catch CanCan error messages
    rescue_from CanCan::AccessDenied do |exception|
      flash[:error] = exception.message
      redirect_to root_url
    end
  
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  # GET /entities
  # GET /entities.xml
  
  load_and_authorize_resource
    
  def index
    @entities = Entity.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @entities }
    end
  end

  # GET /entities/1
  # GET /entities/1.xml
  def show
    @entity = Entity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @entity }
    end
  end

  # GET /entities/new
  # GET /entities/new.xml
  def new
    @entity = Entity.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @entity }
    end
  end

  # GET /entities/1/edit
  def edit
    @entity = Entity.find(params[:id])
  end

  # POST /entities
  # POST /entities.xml
  def create
    @entity = Entity.new(params[:entity])

    respond_to do |format|
      if @entity.save
        format.html { redirect_to(@entity, :notice => 'Entity was successfully created.') }
        format.xml  { render :xml => @entity, :status => :created, :location => @entity }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @entity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /entities/1
  # PUT /entities/1.xml
  def update
    @entity = Entity.find(params[:id])

    respond_to do |format|
      if @entity.update_attributes(params[:entity])
        format.html { redirect_to(@entity, :notice => 'Entity was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @entity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.xml
  def destroy
    @entity = Entity.find(params[:id])
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to(entities_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.xml
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.xml
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.xml
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.xml
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to(@story, :notice => 'Story was successfully created.') }
        format.xml  { render :xml => @story, :status => :created, :location => @story }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.xml
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to(@story, :notice => 'Story was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.xml
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to(stories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  
end

app/helpers/entities_helper.rb
module EntitiesHelper
  
  def assign_entity_type(id)
    if id = 1
      "Person"
    else
      "Company"
    end
  end
  
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/entities/_form.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :user_id, :value => current_user[:id] %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  

  <div class="field">
    <%= f.label :type %>
    <%= select :entity, :entity_type, { "Person" => "1", "Company" => "2" } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render 'form' %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<ul>
<% @entities.each do |entity| %>

    <li><%= link_to entity.name, entity %>
     <span class="<%= entity.entity_name(entity.entity_type) %>" > <%= entity.entity_name(entity.entity_type) %></span>
     <% if user_signed_in? %>
      <%= link_to 'Edit', edit_entity_path(entity) %>
      <%= link_to 'Destroy', entity, :confirm => 'Are you sure?', :method => :delete %>
     <% end %>
    </li>
    
<% end %>
</ul>

<br />


<% if can? :new, @entity %>
    <%= link_to "+ Add New", new_entity_path %>
<% end %>

app/views/entities/new.html.erb
<h1>New entity</h1>

<%= render 'form' %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
   <%= @entity.name %>
</h1>

<p>
    <%= assign_entity_type(@entity.entity_type) %>
</p>


<p>
  <%= @entity.description %>
</p>

<!-- <p>
  <b>Story:</b>
  <%= @entity.story %>
</p> -->



<% if user_signed_in? %>
<%= link_to 'Edit', edit_entity_path(@entity) %> |
<% end %>
<%= link_to 'Back', entities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Matrix</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<header>
  <div id="header-inner" class="wrap">
    <h1>Sharesleuth Matrix</h1>
  </div>
</head>


<article>
<div class="wrap">
 <%= yield %>
</div> 
</article>

<footer>
<div id="footer-inner" class="wrap">
<p>&copy; Sharesleuth.com 2011. All Rights Reserved.</p>
<% if user_signed_in? %>
  You are signed in as <%= link_to( current_user.email, edit_user_registration_path) %>
    <%= link_to('Logout', destroy_user_session_path) %>        
  <% else %>
    <%= link_to('Staff Login', new_user_session_path)  %>  
  <% end %>

<p><small>V Alligator 0.1 Alpha</small></p>

</div>  
</footer>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :byline %><br />
    <%= f.text_field :byline %>
  </div>
  <div class="field">
    <%= f.label :written_at %><br />
    <%= f.date_select :written_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Title</th>
    <th>User</th>
    <th>Byline</th>
    <th>Written at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stories.each do |story| %>
  <tr>
    <td><%= story.url %></td>
    <td><%= story.title %></td>
    <td><%= story.user %></td>
    <td><%= story.byline %></td>
    <td><%= story.written_at %></td>
    <td><%= link_to 'Show', story %></td>
    <td><%= link_to 'Edit', edit_story_path(story) %></td>
    <td><%= link_to 'Destroy', story, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @story.url %>
</p>

<p>
  <b>Title:</b>
  <%= @story.title %>
</p>

<p>
  <b>User:</b>
  <%= @story.user %>
</p>

<p>
  <b>Byline:</b>
  <%= @story.byline %>
</p>

<p>
  <b>Written at:</b>
  <%= @story.written_at %>
</p>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>